#!/bin/bash

set -euo pipefail

# Install prefix defaults to user-local so no sudo is required.
prefix="${1:-$HOME/.local}"

if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists gumbo; then
	echo "Gumbo detected: installed app will include HTML parsing support."
else
	echo "Gumbo not detected: installed app will run without HTML parsing support."
fi

if command -v doxygen >/dev/null 2>&1; then
	echo "Doxygen detected: docs remain optional and are not generated by user install."
else
	echo "Doxygen not detected: no impact on user install."
fi

# Configure the default app-only build (also regenerates desktop launcher metadata).
cmake -S . -B build -DCMAKE_INSTALL_PREFIX="$prefix" -DYTBLND_BUILD_TESTS=OFF -DYTBLND_ENABLE_SQLITE=OFF
# Build application targets without test-only dependencies.
cmake --build build
# Install binaries, resources, icon, and desktop entry into the prefix.
cmake --install build
# Refresh launcher database when available.
update-desktop-database "$prefix/share/applications" 2>/dev/null || true
# Refresh icon cache when available.
gtk-update-icon-cache "$prefix/share/icons/hicolor" 2>/dev/null || true

echo "Installed YTBLND to $prefix"